window.__APP_CONFIG = ({
  apiBaseUrl: "https://meet.localhost",
  wsUrl: "wss://meet.localhost",
  webTransportHost: "https://127.0.0.1:4433",
  oauthEnabled: "true",
  e2eeEnabled: "false",
  webTransportEnabled: "false",
  firefoxEnabled: "false",
  usersAllowedToStream: "",
  serverElectionPeriodMs: 2000,
  audioBitrateKbps: 65,
  videoBitrateKbps: 100,
  screenBitrateKbps: 1200,
  oauthProvider: "google",
  vadThreshold: 0.02,
  oauthAuthUrl: "https://id.localhost/oauth/authorize",
  oauthClientId: "client_01KTPV665WNNP8HZ2DKST4KQZ6",
  oauthRedirectUrl: "https://meet.localhost/auth/callback",
  oauthScopes: "openid email profile",
  oauthTokenUrl: "",
  oauthIssuer: "https://id.localhost",
  oauthPrompt: "",
  oauthFlow: "pkce",
  mockPeersEnabled: "false",
  jmapBaseUrl: ""
});
