window.__APP_CONFIG = Object.freeze({
  apiBaseUrl: "http://localhost:8081",
  wsUrl: "ws://localhost:8080",
  webTransportHost: "https://127.0.0.1:4433",
  oauthEnabled: "true",
  e2eeEnabled: "false",
  webTransportEnabled: "false",
  firefoxEnabled: "false",
  usersAllowedToStream: "",
  serverElectionPeriodMs: 2000,
  audioBitrateKbps: 65,
  videoBitrateKbps: 100,
  screenBitrateKbps: 1200,
  oauthProvider: "foundation",
  vadThreshold: 0.02,
  oauthAuthUrl: "",
  oauthClientId: "client_01KQV3WG023CKND455HPQT37XS",
  oauthRedirectUrl: "http://localhost:3001/auth/callback",
  oauthScopes: "openid email profile",
  oauthTokenUrl: "",
  oauthIssuer: "http://host.docker.internal:8071",
  oauthPrompt: "",
  oauthFlow: "pkce",
  mockPeersEnabled: "false"
});
